test:
  adapter: postgresql
  database: facebook_test
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: facebook_development
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: facebook_production
  pool: 5
  timeout: 5000
